import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/src/app/globals.css";
import RootProvider from "../Provider/RootProvider";
import { Toaster } from "@/src/shared/components/index";
import { SideBar } from "@/src/widgets/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <style precedence="medium" href="fonts">
        @import
        url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Pacifico&display=swap');
      </style>
      <body>
        <RootProvider>
          {/* here */}

          {/* <header className="border-b pb-3">
            <ToggleBtn />
          </header> */}

          <SideBar />

          <Toaster />

          <main className="min-h-full ml-[400px]">{children}</main>
        </RootProvider>
      </body>
    </html>
  );
}
