import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import RootProvider from "../Provider/RootProvider";
import { ToggleBtn } from "@/src/features/toggleTheme";
import { Toaster } from "@/src/shared/components/index";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* here proxy.ts */}
      <body>
        <RootProvider>
          <header className="border-b pb-3">
            <ToggleBtn />
          </header>

          <Toaster />

          <main className="min-h-full">{children}</main>
        </RootProvider>
      </body>
    </html>
  );
}
